application: wtwfappy
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/wtwf.ico
  upload: static/wtwf.ico

- url: /.*
  script: main.app
