application: lookerurl
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /favicon.ico
  static_files: static/wtwf.ico
  upload: static/wtwf.ico

- url: /admin/api/.*
  script: main.app
  login: admin

- url: /admin/.*
  static_files: static/html/admin.html
  upload: static/html/admin.html

- url: /.*
  script: main.app
