runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?_test\.pyc?
- .*\.pyc$

handlers:
- url: /static/(.*\.woff2)
  static_files: static/\1
  upload: static/(.*\.woff2)
  mime_type: font/woff2

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/api/user
  script: main.app
  login: optional

- url: /admin/api/.*
  script: main.app
  login: admin

- url: /admin/add/.*
  script: main.app
  login: admin

- url: /admin/suggest.*
  script: main.app
  login: optional

- url: /admin/suggestxml
  script: main.app
  login: optional

- url: /admin/.*
  static_files: static/admin/admin.html
  upload: static/admin/admin.html
  secure: always

- url: /.well-known/acme-challenge/.*
  script: well_known.app

- url: /.*
  script: main.app
  secure: always
