application: lookerurl
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?_test\.pyc?
- .*\.pyc$

handlers:
- url: /static/fonts/(.*\.woff2)
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.woff2)
  mime_type: font/woff2

- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/api/user
  script: main.app
  login: optional

- url: /admin/api/.*
  script: main.app
  login: admin

- url: /admin/add/.*
  script: main.app
  login: admin

- url: /admin/suggest.*
  script: main.app
  login: optional

- url: /admin/suggestxml
  script: main.app
  login: optional

- url: /admin/.*
  static_files: static/html/admin.html
  upload: static/html/admin.html

- url: /.*
  script: main.app
